# About the project

I'm doing my PhD in a neuroscience research group where most people are focused on (wet) lab work. However, my own interest is more in data science. My earlier MSc studies introduced me to the basics of **R** but now it's time to take the next step. I am delighted that this kind of course exists. I hope it gives me inspiration, and increase and keep up my motivation in this path I have chosen.

I found this course originally in *UEF Yammer* last year.

------------------------------------------------------------------------

My GitHub project-page: <https://github.com/ainopii/IODS-project>

```{r}

date()

```
## The Exercise Set 1

I find this R Markdown "crash course" as a [funny]{style="color: green;"} and easy way to actively learn to use R. Mostly the content was familiar at least some level.

Some new or forgotten basic tools and issues from the first 4 chapters to pick up:

-   pipe operator: %\>% (Ctrl+Shift+M)
-   operating with dates & times
-   different join() -functions (I have used different functions e.g. merge() for this)
-   reshaping data
-   the importance of setting appropriate factor levels (instead of having characters) in plotting and statistical tests

I liked Chapter 4 on the **ggplot2** package showing how to create and play with different type of plots in R. Overall, the R for Health Data Science -book and the R Markdown seems to be helpful and easy to follow.  

*It was great to have clear and detailed instructions for each step (such as the PAT issue) needed to get started with the course.*

> to be continued...  
